version: 2.1

executors:
  aebuilder:
    docker:
      - image: aeternity/builder
        user: builder
    working_directory: ~/src
  docker_builder:
    docker:
      - image: circleci/buildpack-deps:bionic-otp24

jobs:
  verify_rebar_lock:
    executor: aebuilder
    steps:
      - checkout
      - run:
          name: Ensure lock file is up-to-date
          command: |
            ./rebar3 upgrade
            git diff --quiet -- rebar.lock || (echo "rebar.lock is not up-to-date" && exit 1)
  build:
    executor: aebuilder
    steps:
      - checkout
      - restore_cache:
          keys:
            - dialyzer-cache-v1-{{ .Branch }}-{{ .Revision }}
            - dialyzer-cache-v1-{{ .Branch }}-
            - dialyzer-cache-v1-
      - run:
          name: Build
          command: make
      - run:
          name: Static Analysis
          command: rebar3 dialyzer
      - run:
          name: Eunit
          command: rebar3 eunit
      - run:
          name: Common Tests
          command: rebar3 ct
      - save_cache:
          key: dialyzer-cache-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - _build/default/rebar3_20.3.8_plt
      - store_artifacts:
          path: _build/test/logs
  docker_push_tag:
    executor: docker_builder
    environment:
      DOCKERHUB_REPO: aeternity/aesophia_http
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image to DockerHub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t ${DOCKERHUB_REPO:?}:${CIRCLE_TAG:?} -t ${DOCKERHUB_REPO:?}:latest .
            docker push ${DOCKERHUB_REPO:?}:${CIRCLE_TAG:?}
            docker push ${DOCKERHUB_REPO:?}:latest

workflows:
  version: 2
  build_push:
    jobs:
      - verify_rebar_lock
      - build:
          filters:
            tags:
              only: /^v.*$/
      - docker_push_tag:
          context: ae-dockerhub
          requires:
            - build
            - verify_rebar_lock
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*$/
